/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    products: Product;
    documents: Document;
    leads: Lead;
    companies: Company;
    deals: Deal;
    activities: Activity;
    'audit-log': AuditLog;
    'kb-chunks': KbChunk;
    'chat-sessions': ChatSession;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    companies: CompaniesSelect<false> | CompaniesSelect<true>;
    deals: DealsSelect<false> | DealsSelect<true>;
    activities: ActivitiesSelect<false> | ActivitiesSelect<true>;
    'audit-log': AuditLogSelect<false> | AuditLogSelect<true>;
    'kb-chunks': KbChunksSelect<false> | KbChunksSelect<true>;
    'chat-sessions': ChatSessionsSelect<false> | ChatSessionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'home-page': HomePage;
    'about-page': AboutPage;
    'contacts-page': ContactsPage;
    'docs-page': DocsPage;
    'catalog-page': CatalogPage;
    'company-profile': CompanyProfile;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'contacts-page': ContactsPageSelect<false> | ContactsPageSelect<true>;
    'docs-page': DocsPageSelect<false> | DocsPageSelect<true>;
    'catalog-page': CatalogPageSelect<false> | CatalogPageSelect<true>;
    'company-profile': CompanyProfileSelect<false> | CompanyProfileSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Владелец видит всё. Контент-менеджер правит каталог, тексты страниц и фото, но не видит заявки. Менеджер по продажам работает с заявками, сделками и задачами, но не редактирует сайт.
   */
  role: 'owner' | 'admin' | 'manager';
  /**
   * Для уведомлений о заявках. Как узнать: человек запускает бота и пишет @userinfobot. Сейчас Telegram недоступен с сервера, уведомления идут на e-mail.
   */
  telegramChatId?: string | null;
  /**
   * Снимите галочку, чтобы отключить человека, не удаляя его историю
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Фото и файлы. Загружайте JPG, PNG или WebP: сайт сам сделает облегчённые версии. HEIC и PDF как фото не подходят.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Черновик не виден на сайте и не попадает в базу знаний бота. «Предпросмотр» показывает страницу модели до публикации. Чтобы создать похожую модель, откройте существующую и нажмите «Дублировать».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  /**
   * Латиницей, через дефис: forbsa-tt. Адрес страницы: /catalog/<этот адрес>
   */
  slug: string;
  type: 'врезной' | 'накладной';
  series?: string | null;
  /**
   * Нужно для фильтра по ширине двери и для ответов бота
   */
  minDoorWidth?: number | null;
  warranty?: number | null;
  /**
   * Основа ответов чат-бота о модели: пишите конкретно, с цифрами
   */
  features?: string | null;
  package?: string | null;
  recommendation?: string | null;
  compatibleProfiles?: string | null;
  /**
   * JPG, PNG или WebP (не HEIC и не PDF). Первое фото показывается в каталоге
   */
  images?: (number | Media)[] | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  /**
   * Чем меньше число, тем выше модель в каталоге
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  title: string;
  category: 'certificates' | 'drawings' | 'instructions' | 'bim' | 'legal';
  product?: (number | null) | Product;
  file: number | Media;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  company?: string | null;
  phone?: string | null;
  email?: string | null;
  city?: string | null;
  clientType?: ('architect' | 'developer' | 'dealer' | 'installer' | 'individual') | null;
  businessType?: ('wholesale' | 'retail' | 'installation') | null;
  volume?: ('s' | 'm' | 'l') | null;
  comment?: string | null;
  consent?: boolean | null;
  consentAt?: string | null;
  policyVersion?: string | null;
  status?: ('new' | 'progress' | 'done' | 'spam') | null;
  triageNote?: string | null;
  owner?: (number | null) | User;
  linkedCompany?: (number | null) | Company;
  /**
   * Проставляется при конвертации
   */
  linkedDeal?: (number | null) | Deal;
  externalId?: string | null;
  source?: ('site' | 'chatbot' | 'manual' | '1c') | null;
  syncedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies".
 */
export interface Company {
  id: number;
  name: string;
  inn?: string | null;
  kind?: ('dealer' | 'architect' | 'developer' | 'installer' | 'endCustomer') | null;
  city?: string | null;
  website?: string | null;
  contactPerson?: string | null;
  phone?: string | null;
  email?: string | null;
  notes?: string | null;
  owner?: (number | null) | User;
  externalId?: string | null;
  source?: ('site' | 'chatbot' | 'manual' | '1c') | null;
  syncedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deals".
 */
export interface Deal {
  id: number;
  title: string;
  company: number | Company;
  owner: number | User;
  stage: 'proposal' | 'negotiation' | 'won' | 'lost';
  amount?: number | null;
  /**
   * Если заполнено — сумма КП считается по позициям
   */
  positions?:
    | {
        label: string;
        qty?: number | null;
        unitPrice?: number | null;
        id?: string | null;
      }[]
    | null;
  validUntil?: string | null;
  vatIncluded?: boolean | null;
  products?: (number | Product)[] | null;
  expectedCloseAt?: string | null;
  lostReason?: string | null;
  sourceLead?: (number | null) | Lead;
  notes?: string | null;
  externalId?: string | null;
  source?: ('site' | 'chatbot' | 'manual' | '1c') | null;
  syncedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities".
 */
export interface Activity {
  id: number;
  kind: 'call' | 'email' | 'meeting' | 'note';
  subject: string;
  body?: string | null;
  deal?: (number | null) | Deal;
  lead?: (number | null) | Lead;
  author?: (number | null) | User;
  /**
   * Задача = активность со сроком и исполнителем
   */
  assignee?: (number | null) | User;
  priority?: ('low' | 'normal' | 'high') | null;
  dueAt?: string | null;
  doneAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log".
 */
export interface AuditLog {
  id: number;
  action?: ('create' | 'update' | 'delete') | null;
  collectionSlug?: string | null;
  documentId?: string | null;
  user?: (number | null) | User;
  changedFields?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  at?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kb-chunks".
 */
export interface KbChunk {
  id: number;
  source?: string | null;
  refId?: number | null;
  refSlug?: string | null;
  text?: string | null;
  embedding?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-sessions".
 */
export interface ChatSession {
  id: number;
  token?: string | null;
  messages?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  lead?: (number | null) | Lead;
  consent?: boolean | null;
  startedAt?: string | null;
  lastAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'companies';
        value: number | Company;
      } | null)
    | ({
        relationTo: 'deals';
        value: number | Deal;
      } | null)
    | ({
        relationTo: 'activities';
        value: number | Activity;
      } | null)
    | ({
        relationTo: 'audit-log';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'kb-chunks';
        value: number | KbChunk;
      } | null)
    | ({
        relationTo: 'chat-sessions';
        value: number | ChatSession;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  telegramChatId?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  type?: T;
  series?: T;
  minDoorWidth?: T;
  warranty?: T;
  features?: T;
  package?: T;
  recommendation?: T;
  compatibleProfiles?: T;
  images?: T;
  seoTitle?: T;
  seoDescription?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  product?: T;
  file?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  company?: T;
  phone?: T;
  email?: T;
  city?: T;
  clientType?: T;
  businessType?: T;
  volume?: T;
  comment?: T;
  consent?: T;
  consentAt?: T;
  policyVersion?: T;
  status?: T;
  triageNote?: T;
  owner?: T;
  linkedCompany?: T;
  linkedDeal?: T;
  externalId?: T;
  source?: T;
  syncedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies_select".
 */
export interface CompaniesSelect<T extends boolean = true> {
  name?: T;
  inn?: T;
  kind?: T;
  city?: T;
  website?: T;
  contactPerson?: T;
  phone?: T;
  email?: T;
  notes?: T;
  owner?: T;
  externalId?: T;
  source?: T;
  syncedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deals_select".
 */
export interface DealsSelect<T extends boolean = true> {
  title?: T;
  company?: T;
  owner?: T;
  stage?: T;
  amount?: T;
  positions?:
    | T
    | {
        label?: T;
        qty?: T;
        unitPrice?: T;
        id?: T;
      };
  validUntil?: T;
  vatIncluded?: T;
  products?: T;
  expectedCloseAt?: T;
  lostReason?: T;
  sourceLead?: T;
  notes?: T;
  externalId?: T;
  source?: T;
  syncedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities_select".
 */
export interface ActivitiesSelect<T extends boolean = true> {
  kind?: T;
  subject?: T;
  body?: T;
  deal?: T;
  lead?: T;
  author?: T;
  assignee?: T;
  priority?: T;
  dueAt?: T;
  doneAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log_select".
 */
export interface AuditLogSelect<T extends boolean = true> {
  action?: T;
  collectionSlug?: T;
  documentId?: T;
  user?: T;
  changedFields?: T;
  at?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kb-chunks_select".
 */
export interface KbChunksSelect<T extends boolean = true> {
  source?: T;
  refId?: T;
  refSlug?: T;
  text?: T;
  embedding?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-sessions_select".
 */
export interface ChatSessionsSelect<T extends boolean = true> {
  token?: T;
  messages?: T;
  lead?: T;
  consent?: T;
  startedAt?: T;
  lastAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Сохраните как черновик и нажмите «Предпросмотр», чтобы увидеть страницу до публикации. На сайте изменения появятся после «Опубликовать». Пустое поле вернёт прежний текст.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  heroEyebrow?: string | null;
  heroTitle?: string | null;
  /**
   * Показывается оранжевым после заголовка
   */
  heroAccent?: string | null;
  heroLead?: string | null;
  heroCta?: string | null;
  problemTitle?: string | null;
  problemAccent?: string | null;
  numbersTitle?: string | null;
  numbersAccent?: string | null;
  audienceTitle?: string | null;
  audienceSubtitle?: string | null;
  catalogTitle?: string | null;
  /**
   * {count} заменится числом моделей в каталоге. Уберите его, если число показывать не нужно.
   */
  catalogSubtitle?: string | null;
  techTitle?: string | null;
  techLead?: string | null;
  trustTitle?: string | null;
  trustLead?: string | null;
  ctaTitle?: string | null;
  ctaLead?: string | null;
  /**
   * Показывается в поисковой выдаче и во вкладке браузера
   */
  seoTitle?: string | null;
  /**
   * {count} заменится числом моделей.
   */
  seoDescription?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Сохраните как черновик и нажмите «Предпросмотр», чтобы увидеть страницу до публикации. На сайте изменения появятся после «Опубликовать». Пустое поле вернёт прежний текст.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  heroEyebrow?: string | null;
  heroTitle?: string | null;
  heroAccent?: string | null;
  heroLead?: string | null;
  historyTitle?: string | null;
  historyText?: string | null;
  /**
   * Очистите поле, чтобы пометка не показывалась на сайте
   */
  historyNote?: string | null;
  productionTitle?: string | null;
  /**
   * Очистите поле, чтобы пометка не показывалась на сайте
   */
  productionNote?: string | null;
  ctaTitle?: string | null;
  ctaText?: string | null;
  ctaButton?: string | null;
  /**
   * Показывается в поисковой выдаче и во вкладке браузера
   */
  seoTitle?: string | null;
  seoDescription?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Сохраните как черновик и нажмите «Предпросмотр», чтобы увидеть страницу до публикации. На сайте изменения появятся после «Опубликовать». Пустое поле вернёт прежний текст.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts-page".
 */
export interface ContactsPage {
  id: number;
  heroEyebrow?: string | null;
  heroTitle?: string | null;
  heroAccent?: string | null;
  heroLead?: string | null;
  hoursEyebrow?: string | null;
  hoursTitle?: string | null;
  hoursWeekdays?: string | null;
  hoursSaturday?: string | null;
  hoursSunday?: string | null;
  fastReplyTitle?: string | null;
  fastReplyText?: string | null;
  formTitle?: string | null;
  formSubtitle?: string | null;
  /**
   * Показывается в поисковой выдаче и во вкладке браузера
   */
  seoTitle?: string | null;
  seoDescription?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Сохраните как черновик и нажмите «Предпросмотр», чтобы увидеть страницу до публикации. На сайте изменения появятся после «Опубликовать». Пустое поле вернёт прежний текст.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "docs-page".
 */
export interface DocsPage {
  id: number;
  heroEyebrow?: string | null;
  heroTitle?: string | null;
  heroAccent?: string | null;
  heroLead?: string | null;
  ctaTitle?: string | null;
  ctaText?: string | null;
  ctaButton?: string | null;
  /**
   * Показывается в поисковой выдаче и во вкладке браузера
   */
  seoTitle?: string | null;
  seoDescription?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Сохраните как черновик и нажмите «Предпросмотр», чтобы увидеть страницу до публикации. На сайте изменения появятся после «Опубликовать». Пустое поле вернёт прежний текст.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalog-page".
 */
export interface CatalogPage {
  id: number;
  heroTitle?: string | null;
  heroAccent?: string | null;
  heroLead?: string | null;
  ctaTitle?: string | null;
  ctaSubtitle?: string | null;
  ctaButton?: string | null;
  /**
   * Показывается в поисковой выдаче и во вкладке браузера
   */
  seoTitle?: string | null;
  seoDescription?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-profile".
 */
export interface CompanyProfile {
  id: number;
  legalName?: string | null;
  inn?: string | null;
  kpp?: string | null;
  ogrn?: string | null;
  address?: string | null;
  phone?: string | null;
  email?: string | null;
  bankName?: string | null;
  account?: string | null;
  corrAccount?: string | null;
  bik?: string | null;
  signerName?: string | null;
  signerTitle?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  heroEyebrow?: T;
  heroTitle?: T;
  heroAccent?: T;
  heroLead?: T;
  heroCta?: T;
  problemTitle?: T;
  problemAccent?: T;
  numbersTitle?: T;
  numbersAccent?: T;
  audienceTitle?: T;
  audienceSubtitle?: T;
  catalogTitle?: T;
  catalogSubtitle?: T;
  techTitle?: T;
  techLead?: T;
  trustTitle?: T;
  trustLead?: T;
  ctaTitle?: T;
  ctaLead?: T;
  seoTitle?: T;
  seoDescription?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  heroEyebrow?: T;
  heroTitle?: T;
  heroAccent?: T;
  heroLead?: T;
  historyTitle?: T;
  historyText?: T;
  historyNote?: T;
  productionTitle?: T;
  productionNote?: T;
  ctaTitle?: T;
  ctaText?: T;
  ctaButton?: T;
  seoTitle?: T;
  seoDescription?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts-page_select".
 */
export interface ContactsPageSelect<T extends boolean = true> {
  heroEyebrow?: T;
  heroTitle?: T;
  heroAccent?: T;
  heroLead?: T;
  hoursEyebrow?: T;
  hoursTitle?: T;
  hoursWeekdays?: T;
  hoursSaturday?: T;
  hoursSunday?: T;
  fastReplyTitle?: T;
  fastReplyText?: T;
  formTitle?: T;
  formSubtitle?: T;
  seoTitle?: T;
  seoDescription?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "docs-page_select".
 */
export interface DocsPageSelect<T extends boolean = true> {
  heroEyebrow?: T;
  heroTitle?: T;
  heroAccent?: T;
  heroLead?: T;
  ctaTitle?: T;
  ctaText?: T;
  ctaButton?: T;
  seoTitle?: T;
  seoDescription?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalog-page_select".
 */
export interface CatalogPageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroAccent?: T;
  heroLead?: T;
  ctaTitle?: T;
  ctaSubtitle?: T;
  ctaButton?: T;
  seoTitle?: T;
  seoDescription?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-profile_select".
 */
export interface CompanyProfileSelect<T extends boolean = true> {
  legalName?: T;
  inn?: T;
  kpp?: T;
  ogrn?: T;
  address?: T;
  phone?: T;
  email?: T;
  bankName?: T;
  account?: T;
  corrAccount?: T;
  bik?: T;
  signerName?: T;
  signerTitle?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}